// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwYVYmXaG4Baa2samzbJCuAJQ4PcDuI5E',
    appId: '1:622553886007:web:5a724b1e9a112e326fbeb2',
    messagingSenderId: '622553886007',
    projectId: 'my-chat-app-f0bb4',
    authDomain: 'my-chat-app-f0bb4.firebaseapp.com',
    storageBucket: 'my-chat-app-f0bb4.appspot.com',
    measurementId: 'G-15FWKPQW5P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVdHLof1f1n9epzAz0IkH3VNBSfj2Ycko',
    appId: '1:622553886007:android:3bef6bde14425c276fbeb2',
    messagingSenderId: '622553886007',
    projectId: 'my-chat-app-f0bb4',
    storageBucket: 'my-chat-app-f0bb4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBloZcZKvTT5RJZgHLPKw2oFp1gVF5663c',
    appId: '1:622553886007:ios:dcce2b44ca05b5946fbeb2',
    messagingSenderId: '622553886007',
    projectId: 'my-chat-app-f0bb4',
    storageBucket: 'my-chat-app-f0bb4.appspot.com',
    iosBundleId: 'com.example.myChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBloZcZKvTT5RJZgHLPKw2oFp1gVF5663c',
    appId: '1:622553886007:ios:dcce2b44ca05b5946fbeb2',
    messagingSenderId: '622553886007',
    projectId: 'my-chat-app-f0bb4',
    storageBucket: 'my-chat-app-f0bb4.appspot.com',
    iosBundleId: 'com.example.myChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwYVYmXaG4Baa2samzbJCuAJQ4PcDuI5E',
    appId: '1:622553886007:web:c8acb414fbe3997e6fbeb2',
    messagingSenderId: '622553886007',
    projectId: 'my-chat-app-f0bb4',
    authDomain: 'my-chat-app-f0bb4.firebaseapp.com',
    storageBucket: 'my-chat-app-f0bb4.appspot.com',
    measurementId: 'G-54R4HQ17BV',
  );
}
